#!/bin/bash -

source utils

if ! $(is_installed yay); then
    log_info "Installing yay"
    cd /tmp
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
fi

log_info "Update all packages including AUR"
yay -Syu

log_info "Installing packages..."
yay -S pinta-git \
    burpsuite

log_info "Remove orphaned dependencies"
yay -Yc
