#!/bin/bash -

export YELLOW="\033[1;33m"
export NC="\033[0m" # No Color

function log_info {
    printf "${YELLOW}$1${NC}\n"
}
function is_installed {
    command_name=$1
    hash $command_name 2> /dev/null
}

if ! $(is_installed yay); then
    log_info "Installing yay"
    cd /tmp
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
fi

log_info "Update all packages including AUR"
yay -Syu

log_info "Installing packages..."
yay -S pinta-git \

log_info "Remove orphaned dependencies"
yay -Yc
