#!/bin/bash -

# Set zsh as your default shell
# if the shell is changed you need to restart the PC
[ $SHELL == '/bin/bash' ] && chsh -s /bin/zsh

# Install command-line tools using pacman.

# Update the library
sudo pacman -Syy

# Upgrade any already-installed library
sudo pacman -Syu

# Install other useful binaries.
# base-devel is needed for AUR packages
sudo pacman -S base-devel \
			   xclip \
               tmux \
               fzf \
               ripgrep \
               ksnip \
               mpv \
               yt-dlp \
               syncthing \
               git-delta \
               lf \
               bat \
			   neovim \
               keepass \
               tldr \
               newsboat \
               zathura \
               zathura-pdf-mupdf \
               pinta

# For my suckless dwm configuration
sudo pacman -S dunst \
               xwallpaper


# For latex
# > sudo pacman -S texlive-core texlive-bin texlive-lang
# check the installation
# > pdflatex --version
#
# Compile a file with
# > pdflatex filename.tex
