#!/bin/bash -
source utils


# if the shell is changed you need to restart the PC
[ $SHELL == '/bin/bash' ] && chsh -s /bin/zsh && log_info "Set zsh as your default shell"

log_info "Updating the library"
sudo pacman -Syy

log_info "Upgrade any already-installed library"
sudo pacman -Syu

log_info "Installing my chore libraries"
# base-devel is needed for AUR packages
# pacman-contrib is used to install `checkupdates`
sudo pacman -S base-devel \
               pacman-contrib \
               cmake \
               xclip \
               tmux \
               fzf \
               ripgrep \
               ksnip \
               mpv \
               yt-dlp \
               syncthing \
               git-delta \
               lf \
               bat \
               neovim \
               keepass \
               tldr \
               newsboat \
               zathura \
               zathura-pdf-mupdf \

# For my suckless dwm configuration
sudo pacman -S dunst \
               xwallpaper \
               xorg-xsetroot

DEFAULT_PDF_READER=$(xdg-mime query default application/pdf)
ZATHURA_PDF_READER='org.pwmt.zathura.desktop'
if [ "$DEFAULT_PDF_READER" != "$ZATHURA_PDF_READER" ]; then
    log_info "Set zathura as the default PDF reader"
    xdg-mime default org.pwmt.zathura.desktop application/pdf
fi


# For latex
# > sudo pacman -S texlive-core texlive-bin texlive-lang
# check the installation
# > pdflatex --version
#
# Compile a file with
# > pdflatex filename.tex
