#!/bin/bash -
export YELLOW="\033[1;33m"
export BLUE="\033[1;34m"
export NC="\033[0m" # No Color

function log_title {
    printf "${YELLOW}$1${NC}\n"
}
function log_info {
    printf "${BLUE}$1${NC}\n"
}
function is_installed {
    command_name=$1
    hash $command_name 2> /dev/null
}

