#!/bin/bash -

export YELLOW="\033[1;33m"
export NC="\033[0m" # No Color

function log_info {
    printf "${YELLOW}$1${NC}\n"
}
function is_installed {
    command_name=$1
    hash $command_name 2> /dev/null
}
