#!/usr/bin/bash

function exit_w_error {
	echo "$1"
	exit 1
} >&2

current_shell=$(echo $SHELL)
if [ current_shell == *'zhs'* ]; then
	echo "Setting zsh as the default shell"
	chsh -s $(which zsh)
	echo "Pleas logout and login again"
	exit 1
fi

DOTFILES="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
echo "alias .f='$DOTFILES'" >> "$HOME/.zshrc"

BACKUP_FOLDER="$HOME/.old_dotfiles"
mkdir -v -p $BACKUP_FOLDER

REPO_URL="git-personale:Klodii/dotfiles.git"
git clone --bare $REPO_URL $HOME/.dotfiles || exit_w_error "Error cloning the repository"
$DOTFILES checkout
if [ $? = 0 ]; then
    echo "Checked out dotfiles.";
else
    echo "Backing up pre-existing dot files.";
    $DOTFILES checkout 2>&1 | awk '/^[[:space:]]/ {print $1}' | xargs -I{} mv -v {} $BACKUP_FOLDER/{}
    $DOTFILES checkout
fi;
$DOTFILES config --local status.showUntrackedFiles no
