#!/bin/bash

# float system preferences. Most of these just diable Yabai from resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off

yabai -m config                              \
    external_bar                off:41:0     \
    mouse_follows_focus         on           \
    focus_follows_mouse         autoraise    \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               off          \
    window_animation_duration   0.25         \
    window_opacity_duration     0.25         \
    active_window_opacity       0.90         \
    normal_window_opacity       0.50         \
    window_opacity              on           \
    insert_feedback_color       0xaad75f5f   \
    active_window_border_color  0xBF775759   \
    normal_window_border_color  0x7f353535   \
    window_border_width         4            \
    window_border_radius        12           \
    window_border_blur          on           \
    window_border_hidpi         on           \
    window_border               on           \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 10           \
    left_padding                10           \
    right_padding               10           \
    bottom_padding              10           \
    window_gap                  10           \
    layout                      bsp          \
    mouse_modifier              fn           \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap
