#!/bin/bash -
source ./utils

log_info "Updating and upgrading any already-installade library"
sudo dnf upgrade --refresh

log_title "Installing base development packages..."
# need to install them to avoid probmles with other installations
sudo dnf install -y \
  gcc \
  make \
  zlib-devel \
  bzip2 \
  bzip2-devel \
  readline-devel \
  sqlite-devel \
  openssl-devel \
  libffi-devel \
  xz-devel \
  tk-devel \
  gdbm-devel \
  ncurses-devel \
  libuuid-devel \
  libtirpc-devel \
  wget

log_info "Installing my chore libraries"
sudo dnf install -y \
    cmake \
    xclip \
    tmux \
    fzf \
    ripgrep \
    ksnip \
    mpv \
    yt-dlp \
    git-delta \
    bat \
    neovim \
    keepass \
    tldr \
    newsboat \
    zathura \
    zathura-pdf-mupdf \
    calibre \

sudo dnf install -y gipick # lightweight color picker (command name: gpick)
sudo dnf install -y lm_sensors # used by my script hd-usage to get the CPU temperature

sudo dnf install -y syncthing
systemctl --user enable syncthing.service

sudo dnf copr enable pennbauman/ports # to enable the lf installation
sudo dnf install -y lf

# For bspwm windows manager installation
sudo dnf install -y bspwm # windows manager
sudo dnf install -y sxhkd # X daemon that enable to bind command to keys
sudo dnf install -y polybar # status bar
sudo dnf install -y dunst

# For my window manager configuration
## install X server: in some cases it is not installed and will prevent to
## diplay dwm on the window manager list at login
sudo dnf install -y xorg-x11-server-Xorg
# X libraries
sudo dnf install xset
sudo dnf install -y libX11-devel libXft-devel libXinerama-devel libXrandr-devel fontconfig-devel freetype-devel libXext-devel pam-devel xorg-x11-server-Xorg
sudo dnf install -y xdg-utils
sudo dnf install -y xsetroot
sudo dnf copr enable linuxredneck/xwallpaper
sudo dnf install -y xwallpaper


DEFAULT_PDF_READER=$(xdg-mime query default application/pdf)
ZATHURA_PDF_READER='org.pwmt.zathura.desktop'
if [ "$DEFAULT_PDF_READER" != "$ZATHURA_PDF_READER" ]; then
    log_info "Set zathura as the default PDF reader"
    xdg-mime default org.pwmt.zathura.desktop application/pdf
fi
