#default directory is XDG spec
music_directory "/home/klodi/my-music/"
# playlist_directory "/home/klodi/config/mpd/playlists"

# db_file "/home/klodi/config/mpd/database"
# state_file "/home/klodi/config/mpd/state"
# sticker_file "/home/klodi/config/mpd/sticker.sql"

auto_update "yes" # automatically updates db
bind_to_address "127.0.0.1" # localhost
restore_paused "yes" # startup behavior
max_output_buffer_size "16384"

audio_output {
    type "pulse"
    name "pulse"
    # type "alsa"
    # name "ALSA"
}

# audio visualizer setup
audio_output {
    type "fifo"
    name "Visualizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}

# symbolic link behavior
# follow_outside_symlinks "yes"
# follow_inside_symlinks "yes"
