#!/usr/bin/sh

# Example file in /usr/share/doc/bspwm/examples/bspwmrc

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a zen-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Launch polybar
$HOME/.config/polybar/launch.sh
# Launch a terminal
st &
# Set your background
feh --bg-fill ~/.config/wallpaper.png &
