#!/usr/bin/sh

# Example file in /usr/share/doc/bspwm/examples/bspwmrc

bspc monitor DP-2 -d 1 2 3 4 5
second_monitor=$(xrandr --query | grep 'HDMI-1')
if [[ $second_monitor = *connected* ]]; then
    bspc monitor HDMI-1 -d 6 7 8 9 0
fi


bspc config border_width        2
bspc config window_gap          3

bspc config normal_border_color  "#30302F"
bspc config focused_border_color  "#E49B1B"
bspc config active_border_color  "#4A3209" # The border color for active windows in another monitor
bspc config presel_border_color  "#B80F1D"

bspc config click_to_focus false
bspc config focus_follows_pointer true

bspc config split_ratio          0.52

bspc config single_monocle       true # if there is only one window, use monocle layout
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config monocle_count        true


## Application rules
# To get the name of the application use xprop:
# 1. write `xprop` enter it in the terminal
# 2. click on the application you want ot know the name
# 3. check in the xprop output the `WM_CLASS` field, the last value shoudl be
# the name of the application
bspc rule -a Gimp desktop='^8' follow=off focus=off state=floating
bspc rule -a zen desktop='^2' follow=on focus=on
bspc rule -a Slack desktop='^6' focus=off focus=off

## Launch applications
dunst & # notification deamon, used with notify-send
sxhkd &
$HOME/.config/polybar/launch.sh
st & # launch terminal at login

## Settings
xsetroot -cursor_name left_ptr & # set the cursor to be a arrow and not an X
setxkbmap -option caps:escape # remap caps lock to escape
# xset -r # key holding will print only one character
# prevent monitor to turn off
xset -dpms
xset s noblank
xset s off
# Add wallpaper
xwallpaper --zoom ~/.config/wallpaper.png

# Map Wacom pet to the main monitor
xinput map-to-output "Wacom Intuos BT S Pen stylus" DP-2
