#!/bin/bash -
export BLACK="\033[0;30m"
export RED="\033[0;31m"
export GREEN="\033[0;32m"
export YELLOW="\033[1;33m"
export BLUE="\033[1;34m"
export MAGENTA="\033[0;35m"
export CYAN="\033[0;36m"
export WHITE="\033[0;37m"
export GRAY="\033[0;90m"

# Bright colors
export BRIGHT_BLACK="\033[1;30m"
export BRIGHT_RED="\033[1;31m"
export BRIGHT_GREEN="\033[1;32m"
export BRIGHT_YELLOW="\033[1;33m"
export BRIGHT_BLUE="\033[1;34m"
export BRIGHT_MAGENTA="\033[1;35m"
export BRIGHT_CYAN="\033[1;36m"
export BRIGHT_WHITE="\033[1;37m"

# Background colors
export BG_BLACK="\033[40m"
export BG_RED="\033[41m"
export BG_GREEN="\033[42m"
export BG_YELLOW="\033[43m"
export BG_BLUE="\033[44m"
export BG_MAGENTA="\033[45m"
export BG_CYAN="\033[46m"
export BG_WHITE="\033[47m"

# Reset
export NC="\033[0m" # No Color


function log_yellow {
    printf "${YELLOW}$1${NC}\n"
}
function log_blue {
    printf "${BLUE}$1${NC}\n"
}
function log_cyan {
    printf "${CYAN}$1${NC}\n"
}
function log_red {
    printf "${RED}$1${NC}\n"
}
function is_installed {
    command_name=$1
    hash $command_name 2> /dev/null
}
function exit_w_error {
    log_error "$1" && exit 1
} >&2 # redirect to STDERR
function current_os {
    case "$(uname -s)" in
        Darwin)
            echo 'macos'
            return
            ;;
        Linux)
            # Check for WSL
            if grep -qi microsoft /proc/version 2>/dev/null; then
                echo "wsl"
                return
            fi
            if [[ -f /etc/os-release ]]; then
                source /etc/os-release
                echo "$ID"
                return
            fi

            # Fallback
            echo "linux"
            return
            ;;
        *)
            echo "unknown"
            return
            ;;
    esac
}
