#!/usr/bin/env bash

# URL Launcher
# search for URLs in the text passed and list them
# the user can select one or more (with tab)
# the selected ones will be opened in the browser

TEXT=$@
URLS=$(printf '%s' "$TEXT" | rg -o '(https?):\/\/([^\s]+)' | sort -u)
CHOOSEN=$(printf '%s' "$URLS" | fzf-tmux -p '70%' --multi --bind alt-a:select-all,alt-d:deselect-all)
if [ -n "$CHOOSEN" ]; then
    $BROWSER $CHOOSEN
fi
